version: "3.8"

services:
  app:
    image: upendocker98/cicd_github_docker_images:latest
    container_name: myapp
    expose:
      - "8080"   # your app runs on 8080 (adjust if needed)
    networks:
      - mynet
  nginx:
    image: nginx:latest
    container_name: mynginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
